cbv/advpro/urls.py
from django.conf.urls import url
from advpro import views

app_name='advpro'
urlpatterns=[
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
]

cbv/cbv/urls.py
from django.contrib import admin
from django.conf.urls import url
from advpro import views
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.Indexview.as_view()),
    url(r'^advpro/',include('advpro.urls',namespace='advpro')),
]

cbv/advpro/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name=models.CharField(max_length=256)
    principal=models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("advpro:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name=models.CharField(max_length=256)
    age=models.PositiveIntegerField()
    schoo=models.ForeignKey(School,related_name='students',on_delete=models.DO_NOTHING,null=True, blank=True)



    def __str__(self):
        return self.name

cbv/advpro/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView,DeleteView
from . import models
from django.urls import reverse_lazy
from django.http import HttpResponse

"""
normal way
def index(request):
    return render(request,'index.html')
"""
"""
using View method
class Cbv(View):
    def get(self,request):
        return HttpResponse("CLASS BASED VIEWS ARE COOL!")
"""

"""
#using TemplateView

class Indexview(TemplateView):
    template_name='index.html'
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['injectme']='base injectiom'
        return context
        """

class Indexview(TemplateView):
    template_name='index.html'

class SchoolListView(ListView):
    context_oject_name='schools'
    model=models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model =models.School
    template_name = 'advpro/school_details.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields=('name','principal')
    model =models.School

class SchoolDeleteView(DeleteView):
    model =models.School
    success_url= reverse_lazy("advpro:list")

cbv/advpro/templates/advpro/advpro_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'admin:index' %}">admin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%  url 'advpro:list' %}">schools<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">other</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">

    {% block body_block %}
    <h1>hello base page</h1>
    {% endblock %}
</div>

</body>
</html>

cbv/advpro/templates/advpro/school_confirm_delete.html
{% extends "advpro/advpro_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'advpro:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

cbv/advpro/templates/advpro/school_details.html
{% extends "advpro/advpro_base.html" %}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to schools details</h1>
    <h2>school details</h2>
    <p>name:{{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location:{{school_detail.location}}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
    <p>{{student.name}}who is{{student.age}}years old.</p>


    {% endfor %}

</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'advpro:update' pk=school_detail.pk %}">update</a></p>


    </div>
{% endblock %}

cbv/advpro/templates/advpro/school_form.html
{% extends "advpro/advpro_base.html" %}

{% block body_block %}
<h1>
{% if not form.instance.pk %}
create School
{% else %}
Update School
{% endif %}
</h1>
<form method ='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

cbv/advpro/templates/advpro/school_list.html
{% extends "advpro/advpro_base.html" %}

{% block body_block %}

<h1>Welcome tolist of schools</h1>
<ol>
    {% for school in school_list %}
    <h2><li><a href="{{school.id}}">{{ school.name }}</a></li></h2>

    {% endfor %}
</ol>
{% endblock %}