meow/meow/urls.py
from django.contrib import admin
from django.urls import path,include
from persian import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('persian.urls')),
    path('register/',include('persian.urls')),
    path('familydetails/', include('persian.urls')),
]

meow/persian/urls.py
from django.urls import path
from persian import views

app_name='persian'
urlpatterns = [
    path("",views.index,name='index'),
    path("register/",views.form ,name='register'),
    path("familydetails/",views.details,name='famdet'),




]

meow/persian/models.py
from django.db import models
class Family(models.Model):
    girl= models.CharField(max_length=255, unique=True)
    boy=models.CharField(max_length=255, unique=True)
    husky=models.CharField(max_length=255)
    goldie=models.CharField(max_length=255)





# Create your models here.

meow/persian/forms.py
from django import forms
from persian.models import Family
# from django.forms import ModelForm

class Familyform(forms.ModelForm):
    class Meta():
        model=Family
        fields= ('girl','boy','husky','goldie')

meow/persian/views.py
from django.shortcuts import render
from persian.forms import Familyform
from persian.models import Family
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.http import HttpResponse

def index(request):
    return render(request,"persian/Persian.html")

def form(request):
    form=Familyform()

    if request.method=='POST':
        form=Familyform(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

        else:

            print("Error Form invalid")

    return render(request,'persian/register.html',{'form':form})


def details(request):
    famlist= Family.objects.order_by('husky')
    print(famlist)
    famdict={'fam':famlist}
    return render(request,'persian/familydetails.html',famdict)











# Create your views here.

meow/templates/persian/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

<!--
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'persian:index' %}">My World</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'persian:register' %}">Register</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'persian:famdet' %}">details</a>
    </li>
  </ul>
</nav> -->


<nav class="navbar navbar-expand-sm bg-dark navbar-dark"">
  <a class="navbar-brand" href="{% url 'persian:index' %}">My World</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'persian:register' %}">Register<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'persian:famdet' %}">details</a>
      </li>

    </ul>
  </div>
</nav>
<div class= "container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

meow/templates/persian/familydetails.html
{% extends 'persian/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Family details</h1>

</div>
{% if fam %}


    {% for mem in fam %}
    <div class="container">
      <ul>
        <li><h3>girl baby: {{mem.girl}}</h3></li>
        <li><h3>boy baby: {{mem.boy}}</h3></li>
        <li><h3>husky baby: {{ mem.husky }}</h3></li>
        <li><h3>Goldie baby: {{ mem.goldie }}</h3></li>
      </ul>
    </div>
{% endfor %}


{% endif %}



{% endblock %}

meow/templates/persian/persian.html
<!DOCTYPE html>
{% extends 'persian/base.html'%}
{% block body_block %}
{% load staticfiles %}

<div class="container">
  <h2>Sweet Home</h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="{% static 'images/husky.jpg' %}" alt="CAT 1" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'images/goldie.jpg' %}" alt="CAT 2" style="width:100%;">
      </div>
      <div class="item">
        <img src="{% static 'images/papa.jpg' %}" alt="CAT 2" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
{% endblock %}

meow/templates/persian/register.html
{% extends 'persian/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h2>Give names to register</h2>
</div>
<div class="container">
  <form  method="post">
    {{ form.as_p }}
            {%csrf_token%}
    <input type="submit" class="btn btn-primary" value="register">
  </form>
</div>

{% endblock %}