got/got/urls.py
from django.contrib import admin
from django.urls import path
from kingdoms import views
from django.conf import settings
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.Indexview.as_view()),
    url(r'^kingdoms/',include('kingdoms.urls',namespace='kingdoms')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/',include(debug_toolbar.urls))
    ]+ urlpatterns

got/kingdoms/urls.py
from django.conf.urls import url
from kingdoms import views

app_name='kingdoms'
urlpatterns=[
    url(r'^$',views.RegionListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.RegionDetailView.as_view(),name='detail'),
    url(r'^create/$',views.RegionCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.RegionUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.RegionDeleteView.as_view(),name='delete'),
    ]

got/kingdoms/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Region(models.Model):
    name= models.CharField(max_length=256)
    climate = models.CharField(max_length=256)

    def _str_(self):
        return self.name


    def get_absolute_url(self):
        return reverse("kingdoms:detail",kwargs={'pk':self.pk})


class Kingdom(models.Model):
    name= models.CharField(max_length=256)
    king= models.CharField(max_length=256)
    flag= models.CharField(max_length=256)
    reg= models.ForeignKey(Region, related_name='kingdom',on_delete=models.DO_NOTHING,null=True, blank=True)

    def _str_(self):
        return self.name

got/kingdoms/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy
# Create your views here.
class Indexview(TemplateView):
    template_name='index.html'

class RegionListView(ListView):
    model=models.Region

class RegionDetailView(DetailView):
    context_object_name = 'regiondetail'
    model =models.Region
    template_name = 'kingdoms/region_detail.html'

class RegionCreateView(CreateView):
    fields = ('name','climate')
    model = models.Region

class RegionUpdateView(UpdateView):
    fields=('name','climate')
    model =models.Region

class RegionDeleteView(DeleteView):
    model =models.Region
    success_url= reverse_lazy("kingdoms:list")

got/kingdoms/templates/kingdoms/region_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'admin:index' %}">admin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'kingdoms:list' %}">one<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">other</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">

    {% block body_block %}
    <h1>hello base page</h1>
    {% endblock %}
</div>

</body>
</html>

got/kingdoms/templates/kingdoms/region_confirm_delete.html
{% extends "kingdoms/region_base.html" %}

{% block body_block %}
<h1>Delete {{region.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'kingdoms:detail' pk=region.pk %}">Cancel</a>
</form>
{% endblock %}

got/kingdoms/templates/kingdoms/region_detail.html
{% extends "kingdoms/region_base.html" %}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to region details</h1>
    <h2>region details</h2>
    <p>name: {{regiondetail.name}}</p>
    <p>climate: {{regiondetail.climate}}</p>
    </div>

    {% for king in regiondetail.kingdom.all %}
    <p>{{king.name}} is ruled by {{king.king}}.</p>
    <p>the flag is {{king.flag }}</p>


    {% endfor %}

  </div>
  <div class="container">
      <p><a class="btn btn-warning" href="{% url 'kingdoms:update' pk=regiondetail.pk %}">update</a></p>
      <p><a class="btn btn-danger" href="{% url 'kingdoms:delete' pk=regiondetail.pk %}">delete</a></p>


      </div>
{% endblock %}

got/kingdoms/templates/kingdoms/region_form.html
{% extends "kingdoms/region_base.html" %}

{% block body_block %}
<h1>
{% if not form.instance.pk %}
create Region
{% else %}
Update Region
{% endif %}
</h1>
<form method ='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

got/kingdoms/templates/kingdoms/region_list.html
{% extends "kingdoms/region_base.html" %}

{% block body_block %}

<h1>Welcome to list of Regions</h1>
<ol>
    {% for reg in region_list %}
    <h2><li><a href="{{ reg.id }}">{{ reg.name }}</a></li></h2>
    {% endfor %}
</ol>
{% endblock %}